#!/bin/bash
#
# Check needed software for installation is present
#
# Copyright (C) 2014 RUAG Defence, Patrick Haeusermann <patrick.haeusermann@ruag.com>
#
# This file is part of crystalproject
#
# crystalproject is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
#
# crystalproject is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with crystalproject.  If not, see <http://www.gnu.org/licenses/>.

## GLOBALS
BASE_DIR="${BASH_SOURCE[0]%/*/*}"

if [[ "${BASE_DIR}" == *$(basename "${0}")* ]]; then
  BASE_DIR="${PWD%/*}"
fi


## INCLUDES
source "${BASE_DIR}/includes/base.sh" 2>/dev/null
source "${BASE_DIR}/includes/configuration.sh" 2>/dev/null
source "${BASE_DIR}/includes/network_operation.sh" 2>/dev/null


if [[ ${?} -ne 0 ]]; then
  echo "Library inclusion failed. Please verify that all sources are available" >&2
  exit 1
fi

usage() {
  echo -e \
  "Usage: $(basename "${0}") {add|del} HOST\n" \
  "HOST := NAME TYPE PREFIX USER MPGREPREFIX"
  exit 1
}

# check distribution
distribution


case ${1} in
  add)
    shift
    if [[ "${#}" -ne 5 ]]; then
      usage
    fi

    config_add "${@}"

    exit "${?}"
    ;;

  del)
    shift
    if [[ ${#} -lt 1 ]]; then
      usage
    fi

    config_del "${@}"

    exit "${?}"
    ;;

  *)
    usage
    ;;
esac
