#!/bin/bash
#
# Build and deposit
#
# Copyright (C) 2014 RUAG Defence, Patrick Haeusermann <patrick.haeusermann@ruag.com>
#
# This file is part of crystalproject
#
# crystalproject is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
#
# crystalproject is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with crystalproject.  If not, see <http://www.gnu.org/licenses/>.

#TODO put in right directory

## GLOBALS
BASE_DIR=${BASH_SOURCE[0]%/*/*}

if [[ "${BASE_DIR}" == *$(basename "${0}")* ]]; then
  BASE_DIR="${PWD%/*}"
fi

## INCLUDES
source "${BASE_DIR}/includes/base.sh" 2>/dev/null
source "${BASE_DIR}/includes/installation.sh" 2>/dev/null


if [[ "${?}" -ne 0 ]]; then
  echo "Library inclusion failed. Please verify that all sources are available" >&2
  exit 1
fi

check_deps_deb "${BASE_DIR}"/resources/pkglist/ns3

if [[ "${?}" -ne 0 ]]; then
  exit 1
fi

mkdir -p "${BASE_DIR}"/resources/config/ns3/opt/ns3
CURPW=$(pwd)
cp "${BASE_DIR}"/packages/ns3/ns-allinone-3.20.tar.bz2 "${BASE_DIR}"/resources/config/ns3/opt/ns3/
cd "${BASE_DIR}"/resources/config/ns3/opt/ns3
tar xf ns-allinone-3.20.tar.bz2
cd ns-allinone-3.20
./build.py --enable-tests

cd "${CURPW}"

