#!/bin/bash
#
# Build and deposit inside /build
#
# Copyright (C) 2014 RUAG Defence, Patrick Haeusermann <patrick.haeusermann@ruag.com>
#
# This file is part of crystalproject
#
# crystalproject is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
#
# crystalproject is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with crystalproject.  If not, see <http://www.gnu.org/licenses/>.

#TODO put in right directory

## GLOBAL VARS
BASE_DIR=${BASH_SOURCE[0]%/*/*}

if [[ "${BASE_DIR}" == *$(basename "${0}")* ]]; then
  BASE_DIR="${PWD%/*}"
fi

source "${BASE_DIR}/includes/utils/base.sh" 2>/dev/null

inst_apt "${BASE_DIR}/resources/pkglist/ns3"

mkdir -p "${BASE_DIR}"/resources/config/ns3/opt/ns3
CURPW=$(pwd)
cp "${BASE_DIR}"/packages/ns3/ns-allinone-3.20.tar.bz2 "${BASE_DIR}"/resources/config/ns3/opt/ns3/
cd "${BASE_DIR}"/resources/config/ns3/opt/ns3
tar xf ns-allinone-3.20.tar.bz2
cd ns-allinone-3.20
./build.py --enable-tests

cd "${CURPW}"

