#!/bin/bash
#
# Print specs of crystal installation
#
# Copyright (C) 2014 RUAG Defence, Patrick Haeusermann <patrick.haeusermann@ruag.com>
#
# This file is part of crystalproject
#
# crystalproject is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
#
# crystalproject is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with crystalproject.  If not, see <http://www.gnu.org/licenses/>.

## GLOBAL VARS
BASE_DIR="${BASH_SOURCE[0]%/*/*}"

if [[ ${BASE_DIR} == *$(basename "${0}")* ]]; then
  BASE_DIR="${PWD%/*}"
fi



## INCLUDES
source "${BASE_DIR}/includes/network_operation.sh" 2>/dev/null

if [[ ${?} -ne 0 ]]; then
    echo "Script inclusion failed. Please verify that all sources are available" >&2
    exit 1
fi

# print specs
echo "you can login under:"
echo
echo "http://$(hostname -i):9869"

echo "all available connections are the following"
for ip in $(get_ips); do
  echo "http://${ip}:9869"
done

credentials=($(cut -d':' --output-delimiter=' ' -f1,2 /var/lib/one/.one/one_auth))
echo -e "\n\ncredentials:\n\nusername: ${credentials[0]}\npassword: ${credentials[1]}"
